@host = https://api.resourcewatch.org
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzYzcwOTBiZTU5MTU5NmYyN2MxOThjYSIsInJvbGUiOiJBRE1JTiIsInByb3ZpZGVyIjoibG9jYWwiLCJlbWFpbCI6IkNhcmxvcy5EZWxSZWFsLjVAd3JpY29uc3VsdGFudC5vcmciLCJleHRyYVVzZXJEYXRhIjp7ImFwcHMiOlsicnciLCJhcXVlZHVjdCIsImFxdWVkdWN0LXdhdGVyLXJpc2siXX0sImNyZWF0ZWRBdCI6MTY4Njc3NTUyNTAyNSwicGhvdG8iOiJodHRwczovL3MzLmFtYXpvbmF3cy5jb20vd3JpLWFwaS1iYWNrdXBzL3Jlc291cmNld2F0Y2gvc3RhZ2luZy9wcm9maWxlcy9hdmF0YXJzLzAwMC8wMDAvMjU4L29yaWdpbmFsL2RhdGE_MTY3NDA2ODA0NyIsIm5hbWUiOiJDYXJsb3MgRGVsIFJlYWwiLCJpYXQiOjE2ODY3NzU1MjV9.3J7HR6Et_5wmJbbfjnh_7ZvrClzIsRAdwaqMJEMmOuM


### get old dataset
GET {{host}}/v1/dataset/4a2b250e-25ab-4da3-9b83-dc318995eee1
### get metadata old
GET {{host}}/v1/dataset/4a2b250e-25ab-4da3-9b83-dc318995eee1/metadata

### get new dataset
GET {{host}}/v1/dataset/86d9f802-fabf-46e7-83ed-7c5505140208
### get metadata new
GET {{host}}/v1/dataset/86d9f802-fabf-46e7-83ed-7c5505140208/metadata

### Create dataset
PATCH  {{host}}/v1/dataset/86d9f802-fabf-46e7-83ed-7c5505140208/metadata
Content-Type: application/json
Authorization: {{token}}

{
  "application": "aqueduct",
  "language": "en",
  "name": "Crops",
  "description": "\"All crops\" represent all of the crops that are included in the tool as displayed in the menu. Pixels are shaded if they contain at least 10 hectares of crop area within the 10x10 km pixel. If there are multiple crops meeting this criteria per pixel, the predominant crop (based on production) is displayed. If a single crop is selected, and the pixel colors are shaded by level of production. The crop layers displayed on the map reflect 2020 data regardless of the timeframe selected.",
  "info": {
    "sources": [
      {
        "source-url": "http://mapspam.info/",
        "source-name": "MapSPAM 2020"
      }
    ]
  },
  "status": "published"
}