export const CROP_COLOR_DICTIONARY = {
  'arabic coffee': '#A0522D',
  'other cereals': '#FFC0CB',
  'other fibre crops': '#FFF0F5',
  'other oil crops': '#8FBC8F',
  'other pulses': '#87CEFA',
  'other roots': '#DC143C',
  'other tropical fruit': '#FF8C00',
  'other vegetables': '#008000',
  'pearl millet': '#FF1493',
  'pigeon pea': '#1E90FF',
  'rest of crops': '#2F4F4F',
  'robusta coffee': '#8B4513',
  'sesame seed': '#3CB371',
  'small millet': '#FF69B4',
  'sweet potato': '#8B0000',
  'temperate fruit': '#FF6347',
  banana: '#FFD700',
  barley: '#DB7093',
  bean: '#00008B',
  cassava: '#B22222',
  cereals: '#C71585',
  chickpea: '#0000CD',
  citrus: '#FF724C',
  cocoa: '#D2691E',
  coconut: '#6B8E23',
  cotton: '#E6E6FA',
  cowpea: '#0000FF',
  fibres: '#E6E6FA',
  fruit_nuts: '#FFA500',
  groundnut: '#228B22',
  lentil: '#00BFFF',
  maize: '#C71585',
  oilpalm: '#556B2F',
  oilseed_crops: '#6B8E23',
  onion: '#81b622',
  other_crops: '#2F4F4F',
  plantain: '#FFA500',
  potato: '#800000',
  pulses_leguminous: '#0000FF',
  rapeseed: '#2E8B57',
  rice: '#800080',
  roots_tubers: '#A52A2A',
  rubber: '#808080',
  sorghum: '#FFB6C1',
  soybean: '#006400',
  stimulants: '#8B4513',
  sugar_crops: '#FFDAB9',
  sugarbeet: '#FFE4B5',
  sugarcane: '#FFDAB9',
  sunflower: '#808000',
  tea: '#CD853F',
  tobacco: '#DAA520',
  tomato: '#49b622 ',
  wheat: '#4B0082',
  yams: '#A52A2A',
};

export const CROP_OPTIONS = [
  { value: 'all', label: 'All crops' },
  { value: 'arabic coffee', label: 'Arabica coffee', color: CROP_COLOR_DICTIONARY['arabic coffee'] },
  { value: 'banana', label: 'Banana', color: CROP_COLOR_DICTIONARY.banana },
  { value: 'barley', label: 'Barley', color: CROP_COLOR_DICTIONARY.barley },
  { value: 'bean', label: 'Bean', color: CROP_COLOR_DICTIONARY.bean },
  { value: 'cassava', label: 'Cassava', color: CROP_COLOR_DICTIONARY.cassava },
  { value: 'chickpea', label: 'Chickpea', color: CROP_COLOR_DICTIONARY.chickpea },
  { value: 'citrus', label: 'Citrus', color: CROP_COLOR_DICTIONARY.citrus },
  { value: 'cocoa', label: 'Cocoa', color: CROP_COLOR_DICTIONARY.cocoa },
  { value: 'coconut', label: 'Coconut', color: CROP_COLOR_DICTIONARY.coconut },
  { value: 'cotton', label: 'Cotton', color: CROP_COLOR_DICTIONARY.cotton },
  { value: 'cowpea', label: 'Cowpea', color: CROP_COLOR_DICTIONARY.cowpea },
  { value: 'groundnut', label: 'Groundnut', color: CROP_COLOR_DICTIONARY.groundnut },
  { value: 'lentil', label: 'Lentil', color: CROP_COLOR_DICTIONARY.lentil },
  { value: 'maize', label: 'Maize', color: CROP_COLOR_DICTIONARY.maize },
  { value: 'oilpalm', label: 'Oilpalm', color: CROP_COLOR_DICTIONARY.oilpalm },
  { value: 'onion', label: 'Onion', color: CROP_COLOR_DICTIONARY.onion },
  { value: 'other cereals', label: 'Other cereals', color: CROP_COLOR_DICTIONARY['other cereals'] },
  { value: 'other fibre crops', label: 'Other fibres', color: CROP_COLOR_DICTIONARY['other fibre crops'] },
  { value: 'other oil crops', label: 'Other oil crops', color: CROP_COLOR_DICTIONARY['other oil crops'] },
  { value: 'other pulses', label: 'Other pulses', color: CROP_COLOR_DICTIONARY['other pulses'] },
  { value: 'other roots', label: 'Other roots', color: CROP_COLOR_DICTIONARY['other roots'] },
  { value: 'other tropical fruit', label: 'Other Tropical fruit', color: CROP_COLOR_DICTIONARY['other tropical fruit'] },
  { value: 'other vegetables', label: 'Other vegetables', color: CROP_COLOR_DICTIONARY['other vegetables'] },
  { value: 'pearl millet', label: 'Pearl millet', color: CROP_COLOR_DICTIONARY['pearl millet'] },
  { value: 'pigeon pea', label: 'Pigeon pea', color: CROP_COLOR_DICTIONARY['pigeon pea'] },
  { value: 'plantain', label: 'Plantain', color: CROP_COLOR_DICTIONARY.plantain },
  { value: 'potato', label: 'Potato', color: CROP_COLOR_DICTIONARY.potato },
  { value: 'rapeseed', label: 'Rapeseed', color: CROP_COLOR_DICTIONARY.rapeseed },
  { value: 'rest of crops', label: 'Rest of crops', color: CROP_COLOR_DICTIONARY['rest of crops'] },
  { value: 'rice', label: 'Rice', color: CROP_COLOR_DICTIONARY.rice },
  { value: 'robusta coffee', label: 'Robusta coffee', color: CROP_COLOR_DICTIONARY['robusta coffee'] },
  { value: 'rubber', label: 'Rubber', color: CROP_COLOR_DICTIONARY.rubber },
  { value: 'sesame seed', label: 'Sesame seed', color: CROP_COLOR_DICTIONARY['sesame seed'] },
  { value: 'small millet', label: 'Small millet', color: CROP_COLOR_DICTIONARY['small millet'] },
  { value: 'sorghum', label: 'Sorghum', color: CROP_COLOR_DICTIONARY.sorghum },
  { value: 'soybean', label: 'Soybean', color: CROP_COLOR_DICTIONARY.soybean },
  { value: 'sugarbeet', label: 'Sugarbeet', color: CROP_COLOR_DICTIONARY.sugarbeet },
  { value: 'sugarcane', label: 'Sugarcane', color: CROP_COLOR_DICTIONARY.sugarcane },
  { value: 'sunflower', label: 'Sunflower', color: CROP_COLOR_DICTIONARY.sunflower },
  { value: 'sweet potato', label: 'Sweet potato', color: CROP_COLOR_DICTIONARY['sweet potato'] },
  { value: 'tea', label: 'Tea', color: CROP_COLOR_DICTIONARY.tea },
  { value: 'temperate fruit', label: 'Temperate fruit', color: CROP_COLOR_DICTIONARY['temperate fruit'] },
  { value: 'tobacco', label: 'Tobacco', color: CROP_COLOR_DICTIONARY.tobacco },
  { value: 'tomato', label: 'Tomato', color: CROP_COLOR_DICTIONARY.tomato },
  { value: 'wheat', label: 'Wheat', color: CROP_COLOR_DICTIONARY.wheat },
  { value: 'yams', label: 'Yams', color: CROP_COLOR_DICTIONARY.yams }
];

export default {
  CROP_OPTIONS,
  CROP_COLOR_DICTIONARY
};
