# https://api.resourcewatch.org/v1/dataset/db6bb708-5655-4ca7-8e17-ea380048e296/layer/d22fba7c-2cdb-4341-9b33-1b82cfaaec4b

@host = https://api.resourcewatch.org
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzYzcwOTBiZTU5MTU5NmYyN2MxOThjYSIsInJvbGUiOiJBRE1JTiIsInByb3ZpZGVyIjoibG9jYWwiLCJlbWFpbCI6IkNhcmxvcy5EZWxSZWFsLjVAd3JpY29uc3VsdGFudC5vcmciLCJleHRyYVVzZXJEYXRhIjp7ImFwcHMiOlsicnciLCJhcXVlZHVjdCIsImFxdWVkdWN0LXdhdGVyLXJpc2siXX0sImNyZWF0ZWRBdCI6MTY4Njc3NTUyNTAyNSwicGhvdG8iOiJodHRwczovL3MzLmFtYXpvbmF3cy5jb20vd3JpLWFwaS1iYWNrdXBzL3Jlc291cmNld2F0Y2gvc3RhZ2luZy9wcm9maWxlcy9hdmF0YXJzLzAwMC8wMDAvMjU4L29yaWdpbmFsL2RhdGE_MTY3NDA2ODA0NyIsIm5hbWUiOiJDYXJsb3MgRGVsIFJlYWwiLCJpYXQiOjE2ODY3NzU1MjV9.3J7HR6Et_5wmJbbfjnh_7ZvrClzIsRAdwaqMJEMmOuM

@oldDSId = 57748f05-aa1d-476f-9044-9ae9ca8a09c5
@oldLayer = 91659d99-2160-4f80-9475-06e0ddbba862

@newDSId = db6bb708-5655-4ca7-8e17-ea380048e296
@newLayer = d22fba7c-2cdb-4341-9b33-1b82cfaaec4b

### old
GET https://api.resourcewatch.org/v1/dataset/{{oldDSId}}/layer/{{oldLayer}}

### new
GET https://api.resourcewatch.org/v1/dataset/{{newDSId}}/layer/{{newLayer}}

### update new ds
PATCH  {{host}}/v1/dataset/{{newDSId}}/layer/{{newLayer}}
Content-Type: application/json
Authorization: {{token}}

{
    "name": "Pop. at risk of hunger",
    "slug": "Pop-at-risk-of-hunger_3",
    "application": [
        "aqueduct"
    ],
    "provider": "cartodb",
    "default": true,
    "protected": false,
    "published": true,
    "env": "production",
    "layerConfig": {
        "type": "leaflet",
        "params_config": [],
        "sql_config": [
            {
                "key": "where",
                "key_params": [
                    {
                        "key": "year",
                        "required": true
                    }
                ]
            }
        ],
        "body": {
            "url": "https://wri-rw.carto.com/api/v2/sql?q=with s as (SELECT iso, region, value, commodity FROM combined01_prepared_2020v1 {{where}} and impactparameter='Share Pop. at risk of hunger' and iso is not null ), r as (SELECT iso, region, sum(value) as value FROM s group by iso, region), d as (SELECT centroid as geometry, iso, value, region FROM impact_regions_159 t inner join r on new_region=iso) select json_build_object('type','FeatureCollection','features',json_agg(json_build_object('geometry',cast(geometry as json),'properties', json_build_object('value',value,'country',region,'iso',iso, 'unit', 'percentage'),'type','Feature'))) as data from d",
            "use_cors": false
        }
    },
    "legendConfig": {
        "items": [
            {
                "color": "rgba(53, 89, 161, 0.85)",
                "name": "Pop. at risk of hunger"
            }
        ],
        "units": "%",
        "description": "Pop. at risk of hunger represents the percentage of each country's population at risk of suffering from malnourishment. Note that it is not crop specific.",
        "type": "cluster"
    }
}